### ISSUE TITLE
Question: Is this 508 only, or WCAG 2.0?

### ISSUE THREAD

**Issue by Merovex** [benbalter/ra11y#16]
Just curious the level of testing.

**Comment by benbalter** [comment]
Yes. :smile: Via the [Pa11y documentation](https://github.com/nature/pa11y#command-line-interface):

> Section508, WCAG2A, WCAG2AA (default), WCAG2AAA

**Comment by Merovex** [comment]
Cool. Thanks (and close) Like the W2AA default.

On Mon, Nov 23, 2015 at 11:38 AM, Ben Balter notifications@github.com
wrote:

> Yes. [image: :smile:] Via the Pa11y documentation
> https://github.com/nature/pa11y#command-line-interface:
> 
> Section508, WCAG2A, WCAG2AA (default), WCAG2AAA
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benbalter/ra11y/issues/16#issuecomment-158990019.

## 

Ambuletis Digne,
Ben Wilson

We complain because we forget.
